name: nolajyo_project
description: nolajyo_project

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  dio: ^4.0.6
  get: ^4.6.5
  permission_handler: ^10.0.0
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.5.4
  fluttertoast: ^8.0.9

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  
  assets:
    - assets/
    # - assets/img/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  fonts:
    - family: Noto Sans Kr
      fonts:
        - asset: assets/font/Noto_Sans_KR/NotoSansKR-Bold.ttf
        - asset: assets/font/Noto_Sans_KR/NotoSansKR-Light.ttf
        - asset: assets/font/Noto_Sans_KR/NotoSansKR-Medium.ttf
        - asset: assets/font/Noto_Sans_KR/NotoSansKR-Regular.ttf
        - asset: assets/font/Noto_Sans_KR/NotoSansKR-Thin.ttf
  #         style: italic
