name: nolajyo_project
description: nolajyo_project

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dio: ^4.0.6
  get: ^4.6.5
  permission_handler: ^10.0.0
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.5.4
  go_router: ^4.4.1

flutter:

  uses-material-design: true
